%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
#dataset_dir: /home/xiang/dataset/rgbd_dataset_freiburg1_desk
#dataset_dir: /home/wlzkstlz/slambook/slambook-master (1)/slambook-master/project/rgbd_dataset_freiburg1_xyz
dataset_dir:/mnt/hgfs/VMWare-Ubuntu-Shared/rgbd_dataset_freiburg1_room
# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

camera.depth_scale: 5000

# VO paras
number_of_features: 500
scale_factor: 1.2
level_pyramid: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
max_motion_norm:  0.3
#1.0 #5.0
keyframe_rotation: 0.1
keyframe_translation: 0.1


#bundle adjustment
minmum_distance_match_num:  40
use_bundleadjustment: 1
use_ba_pose_only: 1

#local map
mp_min_match_ratio_: 0.3
max_view_angle: 45.0
map_keep_mappoint_size:1000
min_match_mp_num:100
